name: RDP Windows via Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-1.66.4.exe -OutFile tailscale-installer.exe
          Start-Process .\tailscale-installer.exe -ArgumentList "/install /quiet" -Wait
          Start-Sleep -Seconds 10

      - name: Enable RDP
        run: |
          net user runneradmin RdpS3cur3!
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Connect to Tailscale
        run: |
          $tailscale = "${env:ProgramFiles(x86)}\Tailscale IPN\tailscale.exe"
          if (-Not (Test-Path $tailscale)) {
              $tailscale = "${env:ProgramFiles}\Tailscale IPN\tailscale.exe"
          }
          & $tailscale up --authkey tskey-auth-khSHaL1irJ11CNTRL-2DNyUHjZ545zna2iX5as3547ur4dwCu5 --hostname githubrdp
          Start-Sleep -Seconds 5
          & $tailscale ip -4

      - name: Keep Session
        run: ping 127.0.0.1 -t
