name: Windows RDP LocalTunnel

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Node.js + LocalTunnel
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install LocalTunnel & Start Tunnel
      run: |
        npm install -g localtunnel
        net user runneradmin RdpS3cur3!
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        start /B cmd /c "lt --port 3389 --subdomain tesremote > tunnel.log"
        timeout /t 10
        type tunnel.log

    - name: Keep Alive
      run: ping 127.0.0.1 -t
