name: Windows RDP with Remote.it

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup Password
      run: net user runneradmin Gant1Passw0rd!123

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download & Install Remote.it Agent
      run: |
        Invoke-WebRequest -Uri https://downloads.remote.it/agent/windows/remoteit-agent-latest.exe -OutFile remoteit.exe
        Start-Process remoteit.exe -ArgumentList "/VERYSILENT /NORESTART" -Wait
        Start-Sleep -Seconds 10

    - name: Register Device to Remote.it
      run: |
        $code = "ISI_DENGAN_DEVICE_REGISTRATION_CODE"
        & "C:\Program Files (x86)\remoteit\remoteit.exe" register --code $code --name "Github-RDP" --service rdp --port 3389

    - name: Keep Session Alive
      run: while ($true) { Start-Sleep -Seconds 60 }
