name: RDP Windows LocalTunnel

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install LocalTunnel
      run: |
        Invoke-WebRequest -Uri https://github.com/localtunnel/localtunnel/releases/latest/download/lt-windows.exe -OutFile lt.exe

    - name: Start RDP & LocalTunnel
      run: |
        net user runneradmin /add
        net localgroup administrators runneradmin /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Start-Process -FilePath "lt.exe" -ArgumentList "--port 3389 --subdomain tesremote" -NoNewWindow

    - name: Keep Alive
      run: ping 127.0.0.1 -t
