name: RDP Windows via Tailscale

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download & Install Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-1.66.4.exe -OutFile tailscale.exe
        Start-Process .\tailscale.exe -ArgumentList "/install /quiet" -Wait

    - name: Enable RDP & Firewall
      run: |
        net user runneradmin RdpS3cur3!
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Connect to Tailscale Network
      run: |
        $tailscale = "${env:ProgramFiles(x86)}\Tailscale\tailscale.exe"
        if (-Not (Test-Path $tailscale)) {
          $tailscale = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        }
        & $tailscale up --authkey tskey-auth-kTC3EJ6RB911CNTRL-g3xUV9KDmScrtjJhJwjjScUMZYtN3myE --hostname kangadhyrdp

    - name: Show Tailscale IP Address
      run: |
        $tailscale = "${env:ProgramFiles(x86)}\Tailscale\tailscale.exe"
        if (-Not (Test-Path $tailscale)) {
          $tailscale = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        }
        & $tailscale ip -4

    - name: Keep Session Alive
      run: ping 127.0.0.1 -t
