name: Windows RDP LocalTunnel

on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Set Password
        run: net user runneradmin Unixs@rtmed!4

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Start LocalTunnel
        run: |
          lt --port 3389 --subdomain rdpadhy > tunnel.log 2>&1 &
          Start-Sleep -Seconds 10
          Get-Content tunnel.log

      - name: Keep Runner Alive
        run: while ($true) { Start-Sleep -Seconds 60 }
