name: RDP Windows via Tailscale

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Tailscale Portable
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-ipn.exe -OutFile tailscale.exe

    - name: Enable RDP & Firewall
      run: |
        net user runneradmin RdpS3cur3!
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Connect to Tailscale (Portable)
      run: |
        .\tailscale.exe up --authkey tskey-auth-khSHaL1irJ11CNTRL-2DNyUHjZ545zna2iX5as3547ur4dwCu5 --hostname kangadhyrdp

    - name: Show Tailscale IP Address
      run: |
        .\tailscale.exe ip -4

    - name: Keep Session Alive
      run: ping 127.0.0.1 -t
