# =======================================================
# --- CARA YANG BENAR, AMAN, DAN DIREKOMENDASIKAN ---
# =======================================================
name: Windows RDP using Cloudflare (Secure)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up user and enable RDP
        run: |
          net user Administrator "GantiPasswordIni123" /active:yes
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      # Perhatikan baris di bawah ini, ini cara yang aman memanggil token
      - name: Install and Run Cloudflare Tunnel
        run: |
          Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
          Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel", "run", "--token", "${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}" -NoNewWindow

      - name: Keep Runner Alive
        run: |
          echo "RDP siap. Alur kerja akan tetap berjalan selama sekitar 6 jam."
          Start-Sleep -Seconds 21000
